# Generated by Django 5.2.17 on 2026-08-11 17:38

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_administration_and_membership_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_key', models.CharField(max_length=120)),
                ('provider_label', models.CharField(max_length=240)),
                ('model_identifier', models.CharField(blank=True, max_length=240)),
                ('metrics_snapshot', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('headline', models.TextField()),
                ('observations', models.JSONField(blank=True, default=list)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analytics_insights', to='organisations.organisation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_analytics_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['organisation', '-created_at'], name='analytics_insight_org_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('provider_key', ''), _negated=True), name='analytics_insight_provider_not_empty'), models.CheckConstraint(condition=models.Q(('headline', ''), _negated=True), name='analytics_insight_headline_not_empty')],
            },
        ),
    ]
