# Generated by Django 5.2.17 on 2026-08-11 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decision_options', '0002_decisionoption_cost_notes_decisionoption_depends_on_and_more'),
        ('decisions', '0004_decision_organisation_method'),
        ('organisations', '0002_administration_and_membership_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('prompt', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('public_slug', models.CharField(max_length=32, unique=True)),
                ('voting_enabled', models.BooleanField(default=True)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_open_sessions', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='open_sessions', to='decisions.decision')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_sessions', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('promoted', 'Promoted'), ('archived', 'Archived')], default='submitted', max_length=20)),
                ('promoted_to_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promoted_from_idea', to='decision_options.decisionoption')),
                ('submitted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_ideas', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='ideation.opensession')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ideation.opensession')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IdeaVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='ideation.idea')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idea_votes', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='ideation.sessionparticipant')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='idea',
            name='submitted_by_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_ideas', to='ideation.sessionparticipant'),
        ),
        migrations.AddIndex(
            model_name='opensession',
            index=models.Index(fields=['organisation', 'status'], name='open_session_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='opensession',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='open_session_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='opensession',
            constraint=models.CheckConstraint(condition=models.Q(('public_slug', ''), _negated=True), name='open_session_slug_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='opensession',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'open', 'closed', 'archived'])), name='open_session_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='session_participant_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='session_participant_email_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='sessionparticipant',
            constraint=models.UniqueConstraint(fields=('session', 'email'), name='unique_participant_per_session_email'),
        ),
        migrations.AddConstraint(
            model_name='ideavote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('participant__isnull', False), ('user__isnull', True)), models.Q(('participant__isnull', True), ('user__isnull', False)), _connector='OR'), name='idea_vote_exactly_one_identity'),
        ),
        migrations.AddConstraint(
            model_name='ideavote',
            constraint=models.UniqueConstraint(condition=models.Q(('participant__isnull', False)), fields=('idea', 'participant'), name='unique_vote_per_idea_participant'),
        ),
        migrations.AddConstraint(
            model_name='ideavote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('idea', 'user'), name='unique_vote_per_idea_user'),
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['session', 'status'], name='idea_session_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='idea_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['submitted', 'shortlisted', 'promoted', 'archived'])), name='idea_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('submitted_by_participant__isnull', False), ('submitted_by_user__isnull', True)), models.Q(('submitted_by_participant__isnull', True), ('submitted_by_user__isnull', False)), _connector='OR'), name='idea_submitter_exactly_one_identity'),
        ),
    ]
