# Generated by Django 5.2.17 on 2026-08-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='requested_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
