# Generated by Django 5.2.17 on 2026-08-22 05:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideation', '0002_idea_requested_amount'),
        ('workspaces', '0002_seed_default_workspaces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='opensession',
            name='default_workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace used when auto-creating a Decision from a promoted idea.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='open_sessions', to='workspaces.workspace'),
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ideation.idea')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idea_comments', to='ideation.sessionparticipant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='idea_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['idea', 'created_at'], name='idea_comment_idea_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='idea_comment_body_not_empty'), models.CheckConstraint(condition=models.Q(models.Q(('participant__isnull', False), ('user__isnull', True)), models.Q(('participant__isnull', True), ('user__isnull', False)), _connector='OR'), name='idea_comment_exactly_one_identity')],
            },
        ),
    ]
