# Generated by Django 5.2.17 on 2026-08-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0001_initial'),
        ('ideation', '0003_idea_category_opensession_default_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparticipant',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Linked once this email matches a verified persistent applicant account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_participations', to='applicants.applicantaccount'),
        ),
    ]
