# Generated by Django 5.2.17 on 2026-08-24 08:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideation', '0004_sessionparticipant_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='team_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='opensession',
            name='requires_guardian_consent',
            field=models.BooleanField(default=False, help_text='When on, a participant self-declaring as under 18 must record guardian consent to submit.'),
        ),
        migrations.AddField(
            model_name='opensession',
            name='team_submissions_enabled',
            field=models.BooleanField(default=False, help_text='When on, submitters may name a team and list teammates alongside their entry.'),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='age_bracket',
            field=models.CharField(blank=True, choices=[('under_13', 'Under 13'), ('age_13_17', '13-17'), ('age_18_plus', '18 or older')], max_length=20),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='guardian_consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sessionparticipant',
            name='school_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='IdeaTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=60)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='ideation.idea')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='idea_team_member_name_not_empty')],
            },
        ),
    ]
