import { defineCatalog } from "../i18n";

/**
 * French and Portuguese strings are AI-assisted and have not been reviewed
 * by a native speaker - see docs/i18n.md before treating them as final copy.
 */
export const landingCatalog = defineCatalog({
  en: {
    navPlatform: "Platform",
    navHowItWorks: "How it works",
    navWhyUs: "Why us",
    navTrust: "Trust",
    signIn: "Sign in",
    bookAssessment: "Book a fit assessment",
    startFreeCta: "Start my commons, free",
    heroEyebrow: "Free, no invitation required",
    heroLead: "CrowdSmarter is a free platform where a group anticipates what's coming, weighs the evidence, and decides together in the open, with a real record of who decided what and why. The same platform runs funders' grant rounds end to end.",
    heroSecondaryCta: "See how it works",
    trustItem1: "Free to start, no card required",
    trustItem2: "Every disagreement stays visible",
    trustItem3: "Also runs governed grant rounds",
    proofEyebrow: "Where this comes from",
    proofBody: "The approach draws on commons governance, participatory grantmaking, and collective-intelligence research. Start free as a self-organising group, or run a funder's grant round through a guided programme.",
    footerApplicant: "Applicant? Find your applications",
    footerHumanAuthority: "Human authority retained",
    footerTrust: "Trust and security posture",
  },
  fr: {
    navPlatform: "Plateforme",
    navHowItWorks: "Fonctionnement",
    navWhyUs: "Pourquoi nous",
    navTrust: "Confiance",
    signIn: "Se connecter",
    bookAssessment: "Réserver une évaluation d'adéquation",
    startFreeCta: "Créer mon commun, gratuit",
    heroEyebrow: "Gratuit, sans invitation",
    heroLead: "CrowdSmarter est une plateforme gratuite où un groupe anticipe ce qui arrive, pèse les preuves et décide ensemble, ouvertement, avec un véritable historique de qui a décidé quoi et pourquoi. La même plateforme gère aussi les cycles de financement des bailleurs de bout en bout.",
    heroSecondaryCta: "Voir comment ça marche",
    trustItem1: "Gratuit pour démarrer, sans carte requise",
    trustItem2: "Chaque désaccord reste visible",
    trustItem3: "Gère aussi des cycles de financement gouvernés",
    proofEyebrow: "D'où cela vient",
    proofBody: "Cette approche s'appuie sur la gouvernance des communs, le financement participatif et la recherche en intelligence collective. Démarrez gratuitement en tant que groupe auto-organisé, ou lancez le cycle de financement d'un bailleur grâce à un programme guidé.",
    footerApplicant: "Candidat ? Retrouvez vos candidatures",
    footerHumanAuthority: "L'autorité humaine est préservée",
    footerTrust: "Posture de confiance et de sécurité",
  },
  pt: {
    navPlatform: "Plataforma",
    navHowItWorks: "Como funciona",
    navWhyUs: "Por que nós",
    navTrust: "Confiança",
    signIn: "Entrar",
    bookAssessment: "Agendar uma avaliação de adequação",
    startFreeCta: "Criar o meu comum, grátis",
    heroEyebrow: "Grátis, sem necessidade de convite",
    heroLead: "A CrowdSmarter é uma plataforma gratuita onde um grupo antecipa o que vem a seguir, pondera as evidências e decide em conjunto, de forma aberta, com um registo real de quem decidiu o quê e porquê. A mesma plataforma gere também os ciclos de financiamento dos financiadores, do início ao fim.",
    heroSecondaryCta: "Ver como funciona",
    trustItem1: "Grátis para começar, sem cartão necessário",
    trustItem2: "Cada desacordo permanece visível",
    trustItem3: "Também gere ciclos de financiamento governados",
    proofEyebrow: "De onde isto vem",
    proofBody: "Esta abordagem baseia-se na governação de comuns, no financiamento participativo e na investigação sobre inteligência coletiva. Comece gratuitamente como grupo auto-organizado, ou conduza o ciclo de financiamento de um financiador através de um programa guiado.",
    footerApplicant: "Candidato? Encontre as suas candidaturas",
    footerHumanAuthority: "A autoridade humana é mantida",
    footerTrust: "Postura de confiança e segurança",
  },
});
