import { defineCatalog } from "../i18n";

/**
 * French and Arabic strings are AI-assisted and have not been reviewed
 * by a native speaker - see docs/i18n.md before treating them as final copy.
 */
export const landingCatalog = defineCatalog({
  en: {
    navPlatform: "Approach",
    navHowItWorks: "How it works",
    navWhyUs: "Why us",
    navTrust: "Trust",
    signIn: "Sign in",
    bookAssessment: "Discuss a decision",
    startCta: "Set up a commons",
    heroEyebrow: "Facilitation for accountable collective decisions",
    heroLead: "CrowdSmarter facilitates groups to anticipate what's coming, weigh the evidence, and decide together in the open. A supporting platform keeps a clear record of who decided what and why, and can carry a grant round from framing to outcome.",
    heroSecondaryCta: "See how facilitation works",
    trustItem1: "Facilitation shapes the process",
    trustItem2: "Every disagreement stays visible",
    trustItem3: "A supporting platform keeps the record connected",
    proofEyebrow: "Where this comes from",
    proofBody: "Our facilitation approach draws on commons governance, participatory grantmaking, and collective-intelligence research. The platform supports the work by keeping participation, evidence, judgement, and outcomes connected.",
    footerApplicant: "Applicant? Find your applications",
    footerHumanAuthority: "Human authority retained",
    footerTrust: "Trust and security posture",
  },
  fr: {
    navPlatform: "Approche",
    navHowItWorks: "Fonctionnement",
    navWhyUs: "Pourquoi nous",
    navTrust: "Confiance",
    signIn: "Se connecter",
    bookAssessment: "Parler d'une décision",
    startCta: "Configurer un commun",
    heroEyebrow: "Faciliter des décisions collectives responsables",
    heroLead: "CrowdSmarter accompagne les groupes pour anticiper ce qui arrive, examiner les preuves et décider ensemble, ouvertement. Une plateforme de soutien conserve un historique clair de qui a décidé quoi et pourquoi, et peut accompagner un cycle de financement du cadrage au résultat.",
    heroSecondaryCta: "Découvrir notre facilitation",
    trustItem1: "La facilitation structure le processus",
    trustItem2: "Chaque désaccord reste visible",
    trustItem3: "Une plateforme de soutien relie l'ensemble du dossier",
    proofEyebrow: "D'où cela vient",
    proofBody: "Notre approche de facilitation s'appuie sur la gouvernance des communs, le financement participatif et la recherche en intelligence collective. La plateforme soutient ce travail en reliant participation, preuves, jugement et résultats.",
    footerApplicant: "Candidat ? Retrouvez vos candidatures",
    footerHumanAuthority: "L'autorité humaine est préservée",
    footerTrust: "Posture de confiance et de sécurité",
  },
  ar: {
    navPlatform: "النهج",
    navHowItWorks: "كيف تعمل",
    navWhyUs: "لماذا نحن",
    navTrust: "الثقة",
    signIn: "تسجيل الدخول",
    bookAssessment: "ناقش قراراً",
    startCta: "أنشئ مساحة مشتركة",
    heroEyebrow: "تيسير قرارات جماعية مسؤولة",
    heroLead: "تيسّر CrowdSmarter عمل المجموعات لاستشراف ما هو قادم، وموازنة الأدلة، واتخاذ القرار معاً بشفافية. وتحفظ منصة داعمة سجلاً واضحاً يبيّن مَن قرر ماذا ولماذا، ويمكنها مرافقة دورة المنح من التأطير إلى النتائج.",
    heroSecondaryCta: "تعرّف على نهج التيسير",
    trustItem1: "التيسير يشكّل مسار العمل",
    trustItem2: "تظل جميع نقاط الخلاف ظاهرة",
    trustItem3: "منصة داعمة تبقي السجل مترابطاً",
    proofEyebrow: "الأساس الذي ننطلق منه",
    proofBody: "يرتكز نهجنا في التيسير على حوكمة الموارد المشتركة، وتقديم المنح بالمشاركة، وأبحاث الذكاء الجمعي. وتدعم المنصة هذا العمل من خلال ربط المشاركة والأدلة والحكم والنتائج.",
    footerApplicant: "متقدم؟ اعثر على طلباتك",
    footerHumanAuthority: "تبقى السلطة بيد البشر",
    footerTrust: "نهج الثقة والأمان",
  },
});
