import { defineCatalog } from "../i18n";

/**
 * French and Portuguese strings are AI-assisted and have not been reviewed
 * by a native speaker - see docs/i18n.md before treating them as final copy.
 */
export const landingCatalog = defineCatalog({
  en: {
    navPlatform: "Platform",
    navHowItWorks: "How it works",
    navWhyUs: "Why us",
    navTrust: "Trust",
    signIn: "Sign in",
    bookAssessment: "Book a fit assessment",
    heroEyebrow: "Participatory grantmaking",
    heroLead: "One traceable record from open call to award — community input, reviewer scoring, and evidence behind every decision.",
    heroSecondaryCta: "See how it works",
    trustItem1: "Funder-owned records",
    trustItem2: "Reviewer disagreement stays visible",
    trustItem3: "Community voice, not just staff",
    proofEyebrow: "Where this comes from",
    proofBody: "The approach draws on participatory grantmaking and collective-intelligence research, with charter programmes structured around real, funded rounds before wider adoption.",
    footerApplicant: "Applicant? Find your applications",
    footerHumanAuthority: "Human authority retained",
    footerRegions: "Working with organisations across Africa, Europe, and the Middle East",
  },
  fr: {
    navPlatform: "Plateforme",
    navHowItWorks: "Fonctionnement",
    navWhyUs: "Pourquoi nous",
    navTrust: "Confiance",
    signIn: "Se connecter",
    bookAssessment: "Réserver une évaluation d'adéquation",
    heroEyebrow: "Financement participatif",
    heroLead: "Un dossier traçable, de l'appel ouvert à l'attribution — contributions communautaires, notation des évaluateurs et preuves derrière chaque décision.",
    heroSecondaryCta: "Voir comment ça marche",
    trustItem1: "Registres appartenant au bailleur de fonds",
    trustItem2: "Le désaccord des évaluateurs reste visible",
    trustItem3: "La voix de la communauté, pas seulement celle du personnel",
    proofEyebrow: "D'où cela vient",
    proofBody: "Cette approche s'appuie sur la recherche en financement participatif et en intelligence collective, avec des programmes pilotes structurés autour de cycles réels et financés avant une adoption plus large.",
    footerApplicant: "Candidat ? Retrouvez vos candidatures",
    footerHumanAuthority: "L'autorité humaine est préservée",
    footerRegions: "Nous travaillons avec des organisations en Afrique, en Europe et au Moyen-Orient",
  },
  pt: {
    navPlatform: "Plataforma",
    navHowItWorks: "Como funciona",
    navWhyUs: "Por que nós",
    navTrust: "Confiança",
    signIn: "Entrar",
    bookAssessment: "Agendar uma avaliação de adequação",
    heroEyebrow: "Financiamento participativo",
    heroLead: "Um registo rastreável, da chamada aberta à atribuição — contributos da comunidade, pontuação dos avaliadores e evidências por trás de cada decisão.",
    heroSecondaryCta: "Ver como funciona",
    trustItem1: "Registos pertencentes ao financiador",
    trustItem2: "O desacordo dos avaliadores permanece visível",
    trustItem3: "A voz da comunidade, não apenas da equipa",
    proofEyebrow: "De onde isto vem",
    proofBody: "Esta abordagem baseia-se em investigação sobre financiamento participativo e inteligência coletiva, com programas-piloto estruturados em torno de ciclos reais e financiados antes de uma adoção mais ampla.",
    footerApplicant: "Candidato? Encontre as suas candidaturas",
    footerHumanAuthority: "A autoridade humana é mantida",
    footerRegions: "Trabalhamos com organizações em África, na Europa e no Médio Oriente",
  },
});
