import { defineCatalog } from "../i18n";

/**
 * French and Arabic strings are AI-assisted and have not been reviewed
 * by a native speaker - see docs/i18n.md before treating them as final copy.
 */
export const openSessionCatalog = defineCatalog({
  en: {
    joinHeading: "Join to submit an idea and vote",
    joinDescription: "Just your name and email - no account or password needed.",
    nameLabel: "Name",
    emailLabel: "Email",
    joinButton: "Join session",
    joiningButton: "Joining…",
    schoolLabel: "School or institution (optional)",
    ageBracketLabel: "Age",
    ageBracketPlaceholder: "Select your age range",
    ageBracketUnder13: "Under 13",
    ageBracket13to17: "13-17",
    ageBracket18Plus: "18 or older",
    guardianConsentHeading: "Parent or guardian consent",
    guardianConsentDescription: "This session requires a parent or guardian to consent before a participant under 18 can join.",
    guardianNameLabel: "Parent or guardian name",
    guardianEmailLabel: "Parent or guardian email",
    guardianConsentCheckboxLabel: "I am this participant's parent or guardian and I consent to their taking part.",
    teamNameLabel: "Team name (optional)",
    teamMembersLabel: "Teammates",
    teamMemberNamePlaceholder: "Teammate name",
    teamMemberRolePlaceholder: "Role (optional)",
    addTeamMemberButton: "Add teammate",
    removeTeamMemberButton: "Remove",
  },
  fr: {
    joinHeading: "Rejoignez pour soumettre une idée et voter",
    joinDescription: "Juste votre nom et votre e-mail - aucun compte ni mot de passe requis.",
    nameLabel: "Nom",
    emailLabel: "E-mail",
    joinButton: "Rejoindre la session",
    joiningButton: "Connexion en cours…",
    schoolLabel: "École ou établissement (facultatif)",
    ageBracketLabel: "Âge",
    ageBracketPlaceholder: "Sélectionnez votre tranche d'âge",
    ageBracketUnder13: "Moins de 13 ans",
    ageBracket13to17: "13-17 ans",
    ageBracket18Plus: "18 ans ou plus",
    guardianConsentHeading: "Consentement parental ou du tuteur",
    guardianConsentDescription: "Cette session exige le consentement d'un parent ou tuteur avant qu'un participant de moins de 18 ans puisse rejoindre.",
    guardianNameLabel: "Nom du parent ou tuteur",
    guardianEmailLabel: "E-mail du parent ou tuteur",
    guardianConsentCheckboxLabel: "Je suis le parent ou le tuteur de ce participant et je consens à sa participation.",
    teamNameLabel: "Nom de l'équipe (facultatif)",
    teamMembersLabel: "Coéquipiers",
    teamMemberNamePlaceholder: "Nom du coéquipier",
    teamMemberRolePlaceholder: "Rôle (facultatif)",
    addTeamMemberButton: "Ajouter un coéquipier",
    removeTeamMemberButton: "Retirer",
  },
  ar: {
    joinHeading: "انضم لتقديم فكرة والتصويت",
    joinDescription: "كل ما نحتاجه هو اسمك وبريدك الإلكتروني — لا يلزم حساب أو كلمة مرور.",
    nameLabel: "الاسم",
    emailLabel: "البريد الإلكتروني",
    joinButton: "انضم إلى الجلسة",
    joiningButton: "جارٍ الانضمام…",
    schoolLabel: "المدرسة أو المؤسسة (اختياري)",
    ageBracketLabel: "العمر",
    ageBracketPlaceholder: "اختر فئتك العمرية",
    ageBracketUnder13: "أقل من 13 عاماً",
    ageBracket13to17: "من 13 إلى 17 عاماً",
    ageBracket18Plus: "18 عاماً أو أكثر",
    guardianConsentHeading: "موافقة ولي الأمر",
    guardianConsentDescription: "تتطلب هذه الجلسة موافقة أحد الوالدين أو ولي الأمر قبل أن يتمكن المشارك الذي يقل عمره عن 18 عاماً من الانضمام.",
    guardianNameLabel: "اسم أحد الوالدين أو ولي الأمر",
    guardianEmailLabel: "البريد الإلكتروني لأحد الوالدين أو ولي الأمر",
    guardianConsentCheckboxLabel: "أنا والد أو والدة هذا المشارك أو ولي أمره، وأوافق على مشاركته.",
    teamNameLabel: "اسم الفريق (اختياري)",
    teamMembersLabel: "أعضاء الفريق",
    teamMemberNamePlaceholder: "اسم عضو الفريق",
    teamMemberRolePlaceholder: "الدور (اختياري)",
    addTeamMemberButton: "إضافة عضو إلى الفريق",
    removeTeamMemberButton: "إزالة",
  },
});
