# Generated by Django 5.2.17 on 2026-08-22 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decision_options', '0003_decisionoption_awarded_amount_and_more'),
        ('organisations', '0002_administration_and_membership_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provider_key', models.CharField(choices=[('manual', 'Manual ledger'), ('stripe', 'Stripe Connect')], max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed')], max_length=20)),
                ('external_reference', models.CharField(blank=True, default='', max_length=200)),
                ('note', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_disbursements', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='decision_options.decisionoption')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='organisations.organisation')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['option', '-created_at'], name='disbursement_option_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='disbursement_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='OrganisationDisbursementConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_key', models.CharField(choices=[('manual', 'Manual ledger'), ('stripe', 'Stripe Connect')], default='manual', max_length=20)),
                ('stripe_account_id', models.CharField(blank=True, default='', max_length=100)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_configuration', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'organisation disbursement configuration',
                'constraints': [models.CheckConstraint(condition=models.Q(('provider_key__in', ['manual', 'stripe'])), name='disbursement_provider_key_valid')],
            },
        ),
    ]
