# Generated by Django 5.2.16 on 2026-08-03 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0004_decision_organisation_method'),
        ('notifications', '0002_add_collaboration_kind'),
        ('organisations', '0002_administration_and_membership_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_kind_valid',
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('lifecycle', 'Lifecycle'), ('review_due', 'Review Due'), ('ai_review', 'AI Review'), ('membership', 'Membership'), ('collaboration', 'Collaboration'), ('signpost_watch', 'Signpost Watch'), ('system', 'System')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['assignment', 'lifecycle', 'review_due', 'ai_review', 'membership', 'collaboration', 'signpost_watch', 'system'])), name='notification_kind_valid'),
        ),
    ]
