# Generated by Django 5.2.16 on 2026-08-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0002_bootstrap_platform_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformconfiguration',
            name='ai_provider_api_key_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='ai_provider_key',
            field=models.CharField(choices=[('rules', 'Transparent rules (no external service)'), ('anthropic', 'Anthropic Claude')], default='rules', max_length=20),
        ),
        migrations.AddField(
            model_name='platformconfiguration',
            name='ai_provider_model',
            field=models.CharField(default='claude-sonnet-5', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='platformconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('ai_provider_key__in', ['rules', 'anthropic'])), name='platform_ai_provider_key_valid'),
        ),
    ]
