# Generated by Django 5.2.17 on 2026-08-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0003_platformconfiguration_ai_provider_api_key_encrypted_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='platformconfiguration',
            name='platform_ai_provider_key_valid',
        ),
        migrations.AlterField(
            model_name='platformconfiguration',
            name='ai_provider_key',
            field=models.CharField(choices=[('rules', 'Transparent rules (no external service)'), ('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI ChatGPT'), ('gemini', 'Google Gemini')], default='rules', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='platformconfiguration',
            constraint=models.CheckConstraint(condition=models.Q(('ai_provider_key__in', ['rules', 'anthropic', 'openai', 'gemini'])), name='platform_ai_provider_key_valid'),
        ),
    ]
