# Generated by Django 5.2.16 on 2026-08-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionqualityreview',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
