# Generated by Django 5.2.17 on 2026-08-22 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_options', '0003_decisionoption_awarded_amount_and_more'),
        ('organisations', '0002_administration_and_membership_history'),
        ('participants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictOfInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('decision', 'Entire round'), ('option', 'One application')], default='option', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('declared_at', models.DateTimeField()),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('declared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='declared_conflicts_of_interest', to=settings.AUTH_USER_MODEL)),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_of_interest', to='decision_options.decisionoption')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_of_interest', to='organisations.organisation')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_of_interest', to='participants.participant')),
                ('withdrawn_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawn_conflicts_of_interest', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-declared_at', 'id'],
                'indexes': [models.Index(fields=['organisation', 'participant'], name='conflict_org_participant_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('scope__in', ['decision', 'option'])), name='conflict_of_interest_scope_valid'), models.CheckConstraint(condition=models.Q(models.Q(('option__isnull', False), ('scope', 'option')), models.Q(('option__isnull', True), ('scope', 'decision')), _connector='OR'), name='conflict_of_interest_option_required_iff_option_scope'), models.UniqueConstraint(condition=models.Q(('scope', 'option'), ('withdrawn_at__isnull', True)), fields=('participant', 'option'), name='unique_active_option_conflict_per_participant'), models.UniqueConstraint(condition=models.Q(('scope', 'decision'), ('withdrawn_at__isnull', True)), fields=('participant',), name='unique_active_decision_conflict_per_participant')],
            },
        ),
    ]
