# Generated by Django 5.2.16 on 2026-08-03 15:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_administration_and_membership_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('trial_days', models.PositiveIntegerField(default=14)),
                ('max_active_decisions', models.PositiveIntegerField(blank=True, null=True)),
                ('max_active_members', models.PositiveIntegerField(blank=True, null=True)),
                ('includes_advanced_foresight', models.BooleanField(default=True)),
                ('includes_ai_assistance', models.BooleanField(default=True)),
                ('support_level', models.CharField(choices=[('community', 'Community'), ('standard', 'Standard'), ('priority', 'Priority')], default='community', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('key', ''), _negated=True), name='plan_key_not_empty'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='plan_name_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='OrganisationSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('expired', 'Expired')], default='trialing', max_length=20)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_contact_for', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organisations.organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'indexes': [models.Index(fields=['organisation', 'status'], name='billing_org_status_idx')],
            },
        ),
    ]
