# Generated by Django 5.2.16 on 2026-08-03 09:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decisions', '0004_decision_organisation_method'),
        ('organisations', '0002_administration_and_membership_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('measurement_note', models.TextField(blank=True, help_text='How this is measured: scale, unit, or method.')),
                ('direction', models.CharField(choices=[('maximize', 'Higher is better'), ('minimize', 'Lower is better')], max_length=20)),
                ('weight', models.PositiveSmallIntegerField(help_text='Relative weight from 0-100. Weights are compared, not required to sum to 100.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weight_rationale', models.TextField(blank=True)),
                ('is_must_have', models.BooleanField(default=False, help_text='An option failing this threshold cannot be selected.')),
                ('threshold_note', models.TextField(blank=True, help_text='The minimum acceptable bar, in plain language.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_decision_criteria', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='decisions.decision')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_criteria', to='organisations.organisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_decision_criteria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'title', 'id'],
                'indexes': [models.Index(fields=['decision', 'status'], name='criterion_decision_status_idx'), models.Index(fields=['organisation', 'status'], name='criterion_org_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='criterion_title_not_empty'), models.CheckConstraint(condition=models.Q(('weight__gte', 0), ('weight__lte', 100)), name='criterion_weight_between_0_and_100'), models.CheckConstraint(condition=models.Q(('direction__in', ['maximize', 'minimize'])), name='criterion_direction_valid'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'retired'])), name='criterion_status_valid')],
            },
        ),
    ]
