# Generated by Django 5.2.17 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demo_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="demorequest",
            options={
                "ordering": ["-created_at", "id"],
                "verbose_name": "decision enquiry",
                "verbose_name_plural": "decision enquiries",
            },
        ),
        migrations.AlterField(
            model_name="demorequest",
            name="primary_need",
            field=models.CharField(
                choices=[
                    ("strategic_foresight", "Understanding change or uncertainty"),
                    (
                        "decision_governance",
                        "Clarifying authority or the decision process",
                    ),
                    (
                        "collective_intelligence",
                        "Involving relevant people and perspectives",
                    ),
                    (
                        "portfolio_prioritisation",
                        "Comparing options or allocating resources",
                    ),
                    ("organisational_learning", "Following through and learning"),
                    ("other", "Another issue or not sure"),
                ],
                max_length=40,
            ),
        ),
    ]
