# Generated by Django 5.2.17 on 2026-08-22 07:34

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideation', '0003_idea_category_opensession_default_workspace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('portal_token_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
            ],
            options={
                'ordering': ['email'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_applicant_account_email_ci'), models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='applicant_account_email_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='MagicLinkToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_digest', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='applicants.applicantaccount')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='magic_link_account_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_reports', to='applicants.applicantaccount')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='ideation.idea')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'indexes': [models.Index(fields=['idea', '-created_at'], name='progress_report_idea_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('body', ''), _negated=True), name='progress_report_body_not_empty')],
            },
        ),
    ]
