import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useParams } from "react-router";

import { StatusMessage } from "../../components/StatusMessage";
import { ApiError } from "../../lib/api";
import type { AnalyticsInsight, AnalyticsMonthlyTrendPoint, AnalyticsObservation } from "../../lib/types";
import { getOrganisation } from "../organisations/api";
import {
  generateOrganisationAnalyticsInsight,
  getOrganisationAnalytics,
  getOrganisationAnalyticsInsightHistory,
} from "./api";

function valueOrDash(value: number | null, suffix = ""): string {
  return value === null ? "—" : `${value}${suffix}`;
}

function ObservationList({ observations }: { observations: AnalyticsObservation[] }) {
  if (!observations.length) return <p className="muted">No observation was raised.</p>;
  return (
    <div className="ai-finding-list">
      {observations.map((observation, index) => (
        <article className={`ai-finding ai-finding--${observation.severity}`} key={`${observation.title}-${index}`}>
          <span className="role-badge">{observation.severity}</span>
          <h3>{observation.title}</h3>
          <p>{observation.detail}</p>
        </article>
      ))}
    </div>
  );
}

function FlowTrendChart({ points }: { points: AnalyticsMonthlyTrendPoint[] }) {
  const max = Math.max(1, ...points.flatMap((point) => [point.created, point.finalised]));
  const width = 360;
  const height = 180;
  const axisHeight = 22;
  const plotHeight = height - axisHeight;
  const groupWidth = width / Math.max(points.length, 1);
  const barWidth = Math.min(16, groupWidth / 3);
  const summary = points.map((point) => `${point.label}: ${point.created} created, ${point.finalised} finalised`).join("; ");

  return (
    <div className="analytics-trend">
      <svg viewBox={`0 0 ${width} ${height}`} width="100%" style={{ maxWidth: 420 }} role="img" aria-label={`Monthly decision flow. ${summary}`}>
        <line x1={0} y1={plotHeight} x2={width} y2={plotHeight} stroke="var(--line, #d9e1dc)" />
        {points.map((point, index) => {
          const groupX = index * groupWidth + groupWidth / 2;
          const createdHeight = (point.created / max) * (plotHeight - 8);
          const finalisedHeight = (point.finalised / max) * (plotHeight - 8);
          return (
            <g key={point.month}>
              <rect
                x={groupX - barWidth - 2}
                y={plotHeight - createdHeight}
                width={barWidth}
                height={createdHeight}
                rx={2}
                fill="var(--public-green, #1b7a72)"
              >
                <title>{`${point.label}: ${point.created} created`}</title>
              </rect>
              <rect
                x={groupX + 2}
                y={plotHeight - finalisedHeight}
                width={barWidth}
                height={finalisedHeight}
                rx={2}
                fill="#8fb9b0"
              >
                <title>{`${point.label}: ${point.finalised} finalised`}</title>
              </rect>
              <text x={groupX} y={height - 4} fontSize="9" textAnchor="middle" fill="var(--muted, #5a6f6a)">
                {point.label.split(" ")[0]}
              </text>
            </g>
          );
        })}
      </svg>
      <ul className="analytics-trend__legend">
        <li><span style={{ background: "var(--public-green, #1b7a72)" }} />Created</li>
        <li><span style={{ background: "#8fb9b0" }} />Finalised</li>
      </ul>
    </div>
  );
}

function InsightCard({ insight }: { insight: AnalyticsInsight }) {
  const requester = [insight.requested_by.first_name, insight.requested_by.last_name].filter(Boolean).join(" ") || insight.requested_by.email;
  return (
    <div className="analytics-insight__result">
      <p className="analytics-insight__headline">{insight.headline}</p>
      <small className="muted">
        Generated by {insight.provider_label} for {requester} on {new Date(insight.created_at).toLocaleString()}
      </small>
      <ObservationList observations={insight.observations} />
    </div>
  );
}

function AnalyticsInsightPanel({ organisationId }: { organisationId: string }) {
  const queryClient = useQueryClient();
  const historyKey = ["organisations", organisationId, "analytics", "insights"];
  const history = useQuery({ queryKey: historyKey, queryFn: () => getOrganisationAnalyticsInsightHistory(organisationId) });
  const insight = useMutation({
    mutationFn: () => generateOrganisationAnalyticsInsight(organisationId),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: historyKey }),
  });
  const forbidden = insight.error instanceof ApiError && insight.error.status === 403;
  const previousInsights = (history.data ?? []).filter((item) => item.id !== insight.data?.id);
  return (
    <section className="page-primary analytics-insight" aria-label="AI-generated analytics insight">
      <p className="eyebrow">AI-powered</p>
      <h2>Insight narrative</h2>
      <p className="muted">
        Generated on demand from the metrics above by the platform&rsquo;s configured AI provider (transparent rules
        by default; Claude, ChatGPT, or Gemini if an operator has selected and keyed one). Advisory only — it does
        not alter any record. Every generated insight is kept as an attributable record.
      </p>
      <button className="button button--secondary" type="button" disabled={insight.isPending} onClick={() => insight.mutate()}>
        {insight.isPending ? "Generating…" : "Generate insight"}
      </button>
      {forbidden ? <StatusMessage kind="error">Only organisation owners and administrators can generate AI analytics insights.</StatusMessage> : null}
      {insight.isError && !forbidden ? <StatusMessage kind="error">The insight could not be generated.</StatusMessage> : null}
      {insight.data ? <InsightCard insight={insight.data} /> : null}
      {previousInsights.length ? (
        <details className="analytics-insight__history">
          <summary>Previous insights ({previousInsights.length})</summary>
          {previousInsights.map((item) => <InsightCard key={item.id} insight={item} />)}
        </details>
      ) : null}
    </section>
  );
}

export function OrganisationAnalyticsPage() {
  const { organisationId: routeOrganisationId } = useParams<{ organisationId: string }>();
  const organisationId = routeOrganisationId ?? "";
  const organisation = useQuery({ queryKey: ["organisations", organisationId], queryFn: () => getOrganisation(organisationId), enabled: Boolean(organisationId) });
  const analytics = useQuery({ queryKey: ["organisations", organisationId, "analytics"], queryFn: () => getOrganisationAnalytics(organisationId), enabled: Boolean(organisationId) });

  return (
    <div>
      <Link className="back-link" to={`/organisations/${organisationId}`}>← Organisation</Link>
      <div className="page-heading">
        <div><p className="eyebrow">Decision system health</p><h1>{organisation.data?.name ?? "Organisation"} analytics</h1><p className="muted">A small set of explainable measures—not a leaderboard or an automated judgement of decision quality.</p></div>
      </div>
      {analytics.isPending ? <p>Calculating decision metrics…</p> : null}
      {analytics.isError ? <StatusMessage kind="error">Analytics could not be loaded.</StatusMessage> : null}
      {analytics.data ? (
        <>
          <section className="analytics-scorecards" aria-label="Organisation decision totals">
            <article><span>All decisions</span><strong>{analytics.data.totals.decisions}</strong></article>
            <article><span>Open decisions</span><strong>{analytics.data.totals.open_decisions}</strong></article>
            <article><span>Human-finalised</span><strong>{analytics.data.totals.finalised_decisions}</strong></article>
            <article><span>Active lessons</span><strong>{analytics.data.totals.active_lessons}</strong></article>
          </section>
          <div className="analytics-layout">
            <section className="page-primary">
              <p className="eyebrow">Flow</p><h2>Decision movement</h2>
              <FlowTrendChart points={analytics.data.flow.monthly_trend} />
              <dl className="record-grid">
                <div><dt>Created in 90 days</dt><dd>{analytics.data.flow.created_last_90_days}</dd></div>
                <div><dt>Finalised in 90 days</dt><dd>{analytics.data.flow.finalised_last_90_days}</dd></div>
                <div><dt>Median days to finalise</dt><dd>{valueOrDash(analytics.data.flow.median_days_to_finalise)}</dd></div>
                <div><dt>Overdue target dates</dt><dd>{analytics.data.flow.overdue_target_decisions}</dd></div>
                <div className="record-grid__wide"><dt>Open decisions with at least two participants</dt><dd>{valueOrDash(analytics.data.flow.contribution_coverage_percent, "%")}</dd></div>
              </dl>
              <div className="analytics-bars">
                {analytics.data.flow.status_counts.filter((item) => item.count > 0).map((item) => (
                  <div key={item.status}><span>{item.label}</span><div><i style={{ width: `${Math.max(5, item.count / Math.max(analytics.data.totals.decisions, 1) * 100)}%` }} /></div><strong>{item.count}</strong></div>
                ))}
              </div>
            </section>
            <section className="page-primary">
              <p className="eyebrow">Learning</p><h2>Outcomes and follow-through</h2>
              <dl className="record-grid">
                <div><dt>Outcome reviews completed</dt><dd>{analytics.data.learning.outcome_reviews_completed}</dd></div>
                <div><dt>Met or exceeded</dt><dd>{valueOrDash(analytics.data.learning.outcome_success_percent, "%")}</dd></div>
                <div><dt>Reviews due or overdue</dt><dd>{analytics.data.learning.reviews_due_or_overdue}</dd></div>
                <div><dt>Archived decisions</dt><dd>{analytics.data.totals.archived_decisions}</dd></div>
              </dl>
              <h3>Outcome assessments</h3>
              <ul className="analytics-outcomes">{analytics.data.learning.outcome_assessment_counts.map((item) => <li key={item.assessment}><span>{item.label}</span><strong>{item.count}</strong></li>)}</ul>
            </section>
          </div>
          {organisationId ? <AnalyticsInsightPanel organisationId={organisationId} /> : null}
          <section className="analytics-definitions"><h2>How these measures are defined</h2><dl>{Object.entries(analytics.data.definitions).map(([key, definition]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{definition}</dd></div>)}</dl></section>
        </>
      ) : null}
    </div>
  );
}
