import { useMutation, useQuery } from "@tanstack/react-query";
import { Link, useParams } from "react-router";

import { StatusMessage } from "../../components/StatusMessage";
import { ApiError } from "../../lib/api";
import type { AnalyticsObservation } from "../../lib/types";
import { getOrganisation } from "../organisations/api";
import { generateOrganisationAnalyticsInsight, getOrganisationAnalytics } from "./api";

function valueOrDash(value: number | null, suffix = ""): string {
  return value === null ? "—" : `${value}${suffix}`;
}

function ObservationList({ observations }: { observations: AnalyticsObservation[] }) {
  if (!observations.length) return <p className="muted">No observation was raised.</p>;
  return (
    <div className="ai-finding-list">
      {observations.map((observation, index) => (
        <article className={`ai-finding ai-finding--${observation.severity}`} key={`${observation.title}-${index}`}>
          <span className="role-badge">{observation.severity}</span>
          <h3>{observation.title}</h3>
          <p>{observation.detail}</p>
        </article>
      ))}
    </div>
  );
}

function FlowTrendChart({ created, finalised }: { created: number; finalised: number }) {
  const max = Math.max(created, finalised, 1);
  const width = 260;
  const barHeight = 28;
  const gap = 14;
  const labelWidth = 132;
  const trackWidth = width - labelWidth;
  const height = barHeight * 2 + gap;
  const bars = [
    { label: "Created (90 days)", value: created, colour: "var(--public-green, #1b7a72)" },
    { label: "Finalised (90 days)", value: finalised, colour: "#8fb9b0" },
  ];
  return (
    <svg
      viewBox={`0 0 ${width} ${height}`}
      width="100%"
      style={{ maxWidth: 340 }}
      role="img"
      aria-label={`Created ${created} decisions and finalised ${finalised} decisions in the last 90 days`}
    >
      {bars.map((bar, index) => {
        const barWidth = Math.max(2, (bar.value / max) * trackWidth);
        const y = index * (barHeight + gap);
        return (
          <g key={bar.label}>
            <text x={0} y={y + barHeight / 2 + 4} fontSize="11" fill="var(--muted, #5a6f6a)">
              {bar.label}
            </text>
            <rect x={labelWidth} y={y} width={trackWidth} height={barHeight} rx={5} fill="#eef2f0" />
            <rect x={labelWidth} y={y} width={barWidth} height={barHeight} rx={5} fill={bar.colour} />
            <text x={labelWidth + barWidth + 6} y={y + barHeight / 2 + 4} fontSize="12" fontWeight="700" fill="var(--ink, #123d43)">
              {bar.value}
            </text>
          </g>
        );
      })}
    </svg>
  );
}

function AnalyticsInsightPanel({ organisationId }: { organisationId: string }) {
  const insight = useMutation({ mutationFn: () => generateOrganisationAnalyticsInsight(organisationId) });
  const forbidden = insight.error instanceof ApiError && insight.error.status === 403;
  return (
    <section className="page-primary analytics-insight" aria-label="AI-generated analytics insight">
      <p className="eyebrow">AI-powered</p>
      <h2>Insight narrative</h2>
      <p className="muted">
        Generated on demand from the metrics above by the platform&rsquo;s configured AI provider (transparent rules
        by default; Claude, ChatGPT, or Gemini if an operator has selected and keyed one). Advisory only — it does
        not alter any record.
      </p>
      <button className="button button--secondary" type="button" disabled={insight.isPending} onClick={() => insight.mutate()}>
        {insight.isPending ? "Generating…" : insight.data ? "Regenerate insight" : "Generate insight"}
      </button>
      {forbidden ? <StatusMessage kind="error">Only organisation owners and administrators can generate AI analytics insights.</StatusMessage> : null}
      {insight.isError && !forbidden ? <StatusMessage kind="error">The insight could not be generated.</StatusMessage> : null}
      {insight.data ? (
        <div className="analytics-insight__result">
          <p className="analytics-insight__headline">{insight.data.headline}</p>
          <small className="muted">Generated by {insight.data.generated_by}</small>
          <ObservationList observations={insight.data.observations} />
        </div>
      ) : null}
    </section>
  );
}

export function OrganisationAnalyticsPage() {
  const { organisationId: routeOrganisationId } = useParams<{ organisationId: string }>();
  const organisationId = routeOrganisationId ?? "";
  const organisation = useQuery({ queryKey: ["organisations", organisationId], queryFn: () => getOrganisation(organisationId), enabled: Boolean(organisationId) });
  const analytics = useQuery({ queryKey: ["organisations", organisationId, "analytics"], queryFn: () => getOrganisationAnalytics(organisationId), enabled: Boolean(organisationId) });

  return (
    <div>
      <Link className="back-link" to={`/organisations/${organisationId}`}>← Organisation</Link>
      <div className="page-heading">
        <div><p className="eyebrow">Decision system health</p><h1>{organisation.data?.name ?? "Organisation"} analytics</h1><p className="muted">A small set of explainable measures—not a leaderboard or an automated judgement of decision quality.</p></div>
      </div>
      {analytics.isPending ? <p>Calculating decision metrics…</p> : null}
      {analytics.isError ? <StatusMessage kind="error">Analytics could not be loaded.</StatusMessage> : null}
      {analytics.data ? (
        <>
          <section className="analytics-scorecards" aria-label="Organisation decision totals">
            <article><span>All decisions</span><strong>{analytics.data.totals.decisions}</strong></article>
            <article><span>Open decisions</span><strong>{analytics.data.totals.open_decisions}</strong></article>
            <article><span>Human-finalised</span><strong>{analytics.data.totals.finalised_decisions}</strong></article>
            <article><span>Active lessons</span><strong>{analytics.data.totals.active_lessons}</strong></article>
          </section>
          <div className="analytics-layout">
            <section className="page-primary">
              <p className="eyebrow">Flow</p><h2>Decision movement</h2>
              <FlowTrendChart created={analytics.data.flow.created_last_90_days} finalised={analytics.data.flow.finalised_last_90_days} />
              <dl className="record-grid">
                <div><dt>Created in 90 days</dt><dd>{analytics.data.flow.created_last_90_days}</dd></div>
                <div><dt>Finalised in 90 days</dt><dd>{analytics.data.flow.finalised_last_90_days}</dd></div>
                <div><dt>Median days to finalise</dt><dd>{valueOrDash(analytics.data.flow.median_days_to_finalise)}</dd></div>
                <div><dt>Overdue target dates</dt><dd>{analytics.data.flow.overdue_target_decisions}</dd></div>
                <div className="record-grid__wide"><dt>Open decisions with at least two participants</dt><dd>{valueOrDash(analytics.data.flow.contribution_coverage_percent, "%")}</dd></div>
              </dl>
              <div className="analytics-bars">
                {analytics.data.flow.status_counts.filter((item) => item.count > 0).map((item) => (
                  <div key={item.status}><span>{item.label}</span><div><i style={{ width: `${Math.max(5, item.count / Math.max(analytics.data.totals.decisions, 1) * 100)}%` }} /></div><strong>{item.count}</strong></div>
                ))}
              </div>
            </section>
            <section className="page-primary">
              <p className="eyebrow">Learning</p><h2>Outcomes and follow-through</h2>
              <dl className="record-grid">
                <div><dt>Outcome reviews completed</dt><dd>{analytics.data.learning.outcome_reviews_completed}</dd></div>
                <div><dt>Met or exceeded</dt><dd>{valueOrDash(analytics.data.learning.outcome_success_percent, "%")}</dd></div>
                <div><dt>Reviews due or overdue</dt><dd>{analytics.data.learning.reviews_due_or_overdue}</dd></div>
                <div><dt>Archived decisions</dt><dd>{analytics.data.totals.archived_decisions}</dd></div>
              </dl>
              <h3>Outcome assessments</h3>
              <ul className="analytics-outcomes">{analytics.data.learning.outcome_assessment_counts.map((item) => <li key={item.assessment}><span>{item.label}</span><strong>{item.count}</strong></li>)}</ul>
            </section>
          </div>
          {organisationId ? <AnalyticsInsightPanel organisationId={organisationId} /> : null}
          <section className="analytics-definitions"><h2>How these measures are defined</h2><dl>{Object.entries(analytics.data.definitions).map(([key, definition]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{definition}</dd></div>)}</dl></section>
        </>
      ) : null}
    </div>
  );
}
