# Generated by Django 5.2.16 on 2026-08-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionoption',
            name='cost_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='depends_on',
            field=models.ManyToManyField(blank=True, help_text='Options that must also be adopted for this option to work.', related_name='required_by', to='decision_options.decisionoption'),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Estimated cost in the organisation's reporting currency.", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='experiment_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='implementation_time_estimate',
            field=models.CharField(blank=True, help_text="Plain-language estimate, e.g. '3-6 months'.", max_length=120),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='is_experiment',
            field=models.BooleanField(default=False, help_text='A bounded, minimum-viable way to test this option before committing further.'),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='mutually_exclusive_with',
            field=models.ManyToManyField(blank=True, help_text='Options that cannot be selected together with this one.', to='decision_options.decisionoption'),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='resource_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='reversibility',
            field=models.CharField(blank=True, choices=[('easily_reversible', 'Easily reversible'), ('partially_reversible', 'Partially reversible'), ('difficult_to_reverse', 'Difficult to reverse'), ('irreversible', 'Irreversible')], max_length=30),
        ),
    ]
