# Generated by Django 5.2.17 on 2026-08-22 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_options', '0002_decisionoption_cost_notes_decisionoption_depends_on_and_more'),
        ('decisions', '0004_decision_organisation_method'),
        ('organisations', '0002_administration_and_membership_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionoption',
            name='awarded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Amount funded, only meaningful once outcome_status is 'funded'.", max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='eligibility_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='eligibility_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='eligibility_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='eligibility_status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('eligible', 'Eligible'), ('ineligible', 'Ineligible')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='outcome_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='outcome_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outcome_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='outcome_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='decisionoption',
            name='outcome_status',
            field=models.CharField(choices=[('pending', 'Pending decision'), ('funded', 'Funded'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='decisionoption',
            constraint=models.CheckConstraint(condition=models.Q(('eligibility_status__in', ['pending', 'eligible', 'ineligible'])), name='decision_option_eligibility_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='decisionoption',
            constraint=models.CheckConstraint(condition=models.Q(('outcome_status__in', ['pending', 'funded', 'declined'])), name='decision_option_outcome_status_valid'),
        ),
    ]
