# Generated for CrowdSmarter Phase 16.

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0001_initial"),
        ("decisions", "0003_decision_template_provenance"),
        ("decision_options", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacilitationSession",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                ("objective", models.TextField()),
                ("agenda", models.TextField(blank=True)),
                ("participation_guidance", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("planned", "Planned"), ("open", "Open"), ("closed", "Closed"), ("cancelled", "Cancelled")], default="planned", max_length=20)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_facilitation_sessions", to=settings.AUTH_USER_MODEL)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="facilitation_sessions", to="decisions.decision")),
                ("facilitator", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facilitated_sessions", to=settings.AUTH_USER_MODEL)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="facilitation_sessions", to="organisations.organisation")),
            ],
            options={"ordering": ["starts_at", "created_at", "id"]},
        ),
        migrations.CreateModel(
            name="ContributionPreference",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("digest_cadence", models.CharField(choices=[("immediate", "Immediate"), ("daily", "Daily digest"), ("weekly", "Weekly digest"), ("none", "No email digest")], default="daily", max_length=20)),
                ("email_enabled", models.BooleanField(default=False)),
                ("due_reminders_enabled", models.BooleanField(default=True)),
                ("reminder_days_before", models.PositiveSmallIntegerField(default=2)),
                ("last_digest_at", models.DateTimeField(blank=True, null=True)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contribution_preferences", to="organisations.organisation")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contribution_preferences", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["organisation", "user__email"]},
        ),
        migrations.CreateModel(
            name="SessionParticipant",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(choices=[("participant", "Participant"), ("observer", "Observer")], default="participant", max_length=20)),
                ("attendance", models.CharField(choices=[("invited", "Invited"), ("attended", "Attended"), ("absent", "Absent")], default="invited", max_length=20)),
                ("added_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="added_facilitation_participants", to=settings.AUTH_USER_MODEL)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="facilitation_participants", to="organisations.organisation")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="participants", to="contributions.facilitationsession")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facilitation_participations", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["role", "user__email", "id"]},
        ),
        migrations.CreateModel(
            name="ContributionRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("evidence", "Evidence"), ("assumption", "Assumption"), ("risk", "Risk"), ("stakeholder", "Stakeholder perspective"), ("option", "Option"), ("question", "Question response"), ("review", "Review"), ("scenario", "Scenario contribution"), ("implementation", "Implementation input"), ("other", "Other")], max_length=30)),
                ("title", models.CharField(max_length=240)),
                ("instructions", models.TextField()),
                ("priority", models.CharField(choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("critical", "Critical")], default="normal", max_length=20)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("open", "Open"), ("in_progress", "In progress"), ("submitted", "Submitted"), ("under_review", "Under review"), ("accepted", "Accepted"), ("returned", "Returned"), ("cancelled", "Cancelled")], default="draft", max_length=20)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("assignee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assigned_contributions", to=settings.AUTH_USER_MODEL)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contribution_requests", to="decisions.decision")),
                ("option", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contribution_requests", to="decision_options.decisionoption")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contribution_requests", to="organisations.organisation")),
                ("requested_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requested_contributions", to=settings.AUTH_USER_MODEL)),
                ("reviewer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_contribution_requests", to=settings.AUTH_USER_MODEL)),
                ("session", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contribution_requests", to="contributions.facilitationsession")),
            ],
            options={"ordering": ["due_at", "-priority", "created_at", "id"]},
        ),
        migrations.CreateModel(
            name="ContributionSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("body", models.TextField()),
                ("references", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted")], default="draft", max_length=20)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contribution_submissions", to=settings.AUTH_USER_MODEL)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contribution_submissions", to="decisions.decision")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contribution_submissions", to="organisations.organisation")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="contributions.contributionrequest")),
            ],
            options={"ordering": ["request", "sequence", "id"]},
        ),
        migrations.CreateModel(
            name="ContributionReview",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("outcome", models.CharField(choices=[("accepted", "Accepted"), ("returned", "Returned"), ("comment", "Comment")], max_length=20)),
                ("note", models.TextField()),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contribution_reviews", to="decisions.decision")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="contribution_reviews", to="organisations.organisation")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="contributions.contributionrequest")),
                ("reviewer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contribution_reviews", to=settings.AUTH_USER_MODEL)),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reviews", to="contributions.contributionsubmission")),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.AddIndex(model_name="facilitationsession", index=models.Index(fields=["decision", "status", "starts_at"], name="fac_session_decision_idx")),
        migrations.AddIndex(model_name="facilitationsession", index=models.Index(fields=["organisation", "facilitator", "status"], name="fac_session_facilitator_idx")),
        migrations.AddConstraint(model_name="facilitationsession", constraint=models.CheckConstraint(condition=models.Q(status__in=["planned", "open", "closed", "cancelled"]), name="facilitation_session_status_valid")),
        migrations.AddConstraint(model_name="facilitationsession", constraint=models.CheckConstraint(condition=~models.Q(title=""), name="facilitation_session_title_not_empty")),
        migrations.AddConstraint(model_name="facilitationsession", constraint=models.CheckConstraint(condition=~models.Q(objective=""), name="facilitation_session_objective_not_empty")),
        migrations.AddConstraint(model_name="contributionpreference", constraint=models.UniqueConstraint(fields=("organisation", "user"), name="one_contribution_preference_per_org_user")),
        migrations.AddConstraint(model_name="contributionpreference", constraint=models.CheckConstraint(condition=models.Q(digest_cadence__in=["immediate", "daily", "weekly", "none"]), name="contribution_digest_cadence_valid")),
        migrations.AddConstraint(model_name="contributionpreference", constraint=models.CheckConstraint(condition=models.Q(reminder_days_before__gte=0, reminder_days_before__lte=30), name="contribution_reminder_days_range")),
        migrations.AddConstraint(model_name="sessionparticipant", constraint=models.UniqueConstraint(fields=("session", "user"), name="one_user_per_facilitation_session")),
        migrations.AddConstraint(model_name="sessionparticipant", constraint=models.CheckConstraint(condition=models.Q(role__in=["participant", "observer"]), name="session_participant_role_valid")),
        migrations.AddConstraint(model_name="sessionparticipant", constraint=models.CheckConstraint(condition=models.Q(attendance__in=["invited", "attended", "absent"]), name="session_participant_attendance_valid")),
        migrations.AddIndex(model_name="contributionrequest", index=models.Index(fields=["decision", "status", "due_at"], name="contribution_decision_idx")),
        migrations.AddIndex(model_name="contributionrequest", index=models.Index(fields=["assignee", "status", "due_at"], name="contribution_assignee_idx")),
        migrations.AddIndex(model_name="contributionrequest", index=models.Index(fields=["organisation", "status", "priority"], name="contribution_org_status_idx")),
        migrations.AddConstraint(model_name="contributionrequest", constraint=models.CheckConstraint(condition=models.Q(kind__in=["evidence", "assumption", "risk", "stakeholder", "option", "question", "review", "scenario", "implementation", "other"]), name="contribution_request_kind_valid")),
        migrations.AddConstraint(model_name="contributionrequest", constraint=models.CheckConstraint(condition=models.Q(status__in=["draft", "open", "in_progress", "submitted", "under_review", "accepted", "returned", "cancelled"]), name="contribution_request_status_valid")),
        migrations.AddConstraint(model_name="contributionrequest", constraint=models.CheckConstraint(condition=models.Q(priority__in=["low", "normal", "high", "critical"]), name="contribution_request_priority_valid")),
        migrations.AddConstraint(model_name="contributionrequest", constraint=models.CheckConstraint(condition=~models.Q(title=""), name="contribution_request_title_not_empty")),
        migrations.AddConstraint(model_name="contributionrequest", constraint=models.CheckConstraint(condition=~models.Q(instructions=""), name="contribution_request_instructions_not_empty")),
        migrations.AddConstraint(model_name="contributionsubmission", constraint=models.UniqueConstraint(fields=("request", "sequence"), name="contribution_submission_sequence_unique")),
        migrations.AddConstraint(model_name="contributionsubmission", constraint=models.UniqueConstraint(condition=models.Q(status="draft"), fields=("request", "author"), name="one_contribution_draft_per_author")),
        migrations.AddConstraint(model_name="contributionsubmission", constraint=models.CheckConstraint(condition=models.Q(status__in=["draft", "submitted"]), name="contribution_submission_status_valid")),
        migrations.AddConstraint(model_name="contributionsubmission", constraint=models.CheckConstraint(condition=~models.Q(body=""), name="contribution_submission_body_not_empty")),
        migrations.AddIndex(model_name="contributionsubmission", index=models.Index(fields=["request", "status", "-sequence"], name="contribution_submission_idx")),
        migrations.AddConstraint(model_name="contributionreview", constraint=models.CheckConstraint(condition=models.Q(outcome__in=["accepted", "returned", "comment"]), name="contribution_review_outcome_valid")),
        migrations.AddConstraint(model_name="contributionreview", constraint=models.CheckConstraint(condition=~models.Q(note=""), name="contribution_review_note_not_empty")),
    ]
