# Generated by Django 5.2.17 on 2026-09-03 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_offline_session_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitationAgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('purpose', models.TextField(blank=True)),
                ('method', models.CharField(blank=True, max_length=240)),
                ('facilitator_prompt', models.TextField(blank=True)),
                ('output_prompt', models.TextField(blank=True)),
                ('planned_minutes', models.PositiveSmallIntegerField(default=10)),
                ('order', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('active', 'Active'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_facilitation_agenda_items', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='contributions.facilitationsession')),
            ],
            options={
                'ordering': ['order', 'created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='facilitationrecord',
            name='agenda_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='contributions.facilitationagendaitem'),
        ),
        migrations.AddIndex(
            model_name='facilitationagendaitem',
            index=models.Index(fields=['session', 'status', 'order'], name='fac_agenda_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilitationagendaitem',
            constraint=models.UniqueConstraint(fields=('session', 'order'), name='one_facilitation_agenda_order'),
        ),
        migrations.AddConstraint(
            model_name='facilitationagendaitem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('session',), name='one_active_facilitation_agenda_item'),
        ),
        migrations.AddConstraint(
            model_name='facilitationagendaitem',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='facilitation_agenda_title_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='facilitationagendaitem',
            constraint=models.CheckConstraint(condition=models.Q(('planned_minutes__gte', 1), ('planned_minutes__lte', 480)), name='facilitation_agenda_minutes_range'),
        ),
        migrations.AddConstraint(
            model_name='facilitationagendaitem',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['queued', 'active', 'completed', 'skipped'])), name='facilitation_agenda_status_valid'),
        ),
    ]
