# Generated by Django 5.2.17 on 2026-09-03 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_facilitationagendaitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitationsession',
            name='accessibility_arrangements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='facilitationsession',
            name='consent_boundary',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='FacilitationQualityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inclusion_score', models.PositiveSmallIntegerField()),
                ('clarity_score', models.PositiveSmallIntegerField()),
                ('neutrality_score', models.PositiveSmallIntegerField()),
                ('participation_score', models.PositiveSmallIntegerField()),
                ('follow_through_score', models.PositiveSmallIntegerField()),
                ('what_worked', models.TextField()),
                ('improve_next_time', models.TextField()),
                ('unresolved_risks', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField()),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilitation_quality_reviews', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_review', to='contributions.facilitationsession')),
            ],
            options={
                'ordering': ['-reviewed_at', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('inclusion_score__gte', 1), ('inclusion_score__lte', 5)), name='fac_quality_inclusion_range'), models.CheckConstraint(condition=models.Q(('clarity_score__gte', 1), ('clarity_score__lte', 5)), name='fac_quality_clarity_range'), models.CheckConstraint(condition=models.Q(('neutrality_score__gte', 1), ('neutrality_score__lte', 5)), name='fac_quality_neutrality_range'), models.CheckConstraint(condition=models.Q(('participation_score__gte', 1), ('participation_score__lte', 5)), name='fac_quality_participation_range'), models.CheckConstraint(condition=models.Q(('follow_through_score__gte', 1), ('follow_through_score__lte', 5)), name='fac_quality_follow_through_range'), models.CheckConstraint(condition=models.Q(('what_worked', ''), _negated=True), name='fac_quality_what_worked_not_empty'), models.CheckConstraint(condition=models.Q(('improve_next_time', ''), _negated=True), name='fac_quality_improvement_not_empty')],
            },
        ),
    ]
