# Generated for CrowdSmarter Phase 14.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organisations", "0001_initial"),
        ("decisions", "0003_decision_template_provenance"),
        ("decision_options", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationExercise",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                ("purpose", models.TextField(blank=True)),
                ("method", models.CharField(choices=[("scorecard", "Multi-criteria scorecard"), ("approval", "Approval voting"), ("consent", "Consent and objections"), ("delphi", "Delphi evaluation")], default="scorecard", max_length=24)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("open", "Open"), ("closed", "Closed"), ("archived", "Archived")], default="draft", max_length=20)),
                ("anonymity", models.CharField(choices=[("attributed", "Attributable"), ("peer_anonymous", "Anonymous to peers")], default="attributed", max_length=24)),
                ("blind_results_until_close", models.BooleanField(default=True)),
                ("quorum_count", models.PositiveIntegerField(default=1)),
                ("approval_threshold", models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ("objection_threshold", models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_evaluation_exercises", to=settings.AUTH_USER_MODEL)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_exercises", to="decisions.decision")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_exercises", to="organisations.organisation")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_evaluation_exercises", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at", "title", "id"]},
        ),
        migrations.CreateModel(
            name="PrioritisationPortfolio",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                ("purpose", models.TextField(blank=True)),
                ("budget_limit", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("capacity_limit", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("open", "Open for assessment"), ("closed", "Closed"), ("archived", "Archived")], default="draft", max_length=20)),
                ("anonymity", models.CharField(choices=[("attributed", "Attributable"), ("peer_anonymous", "Anonymous to peers")], default="attributed", max_length=24)),
                ("blind_results_until_close", models.BooleanField(default=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_prioritisation_portfolios", to=settings.AUTH_USER_MODEL)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="prioritisation_portfolios", to="organisations.organisation")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_prioritisation_portfolios", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at", "title", "id"]},
        ),
        migrations.CreateModel(
            name="EvaluationCriterion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("weight", models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ("scale_min", models.PositiveSmallIntegerField(default=1)),
                ("scale_max", models.PositiveSmallIntegerField(default=5)),
                ("higher_is_better", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="criteria", to="evaluations.evaluationexercise")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_criteria", to="organisations.organisation")),
            ],
            options={"ordering": ["order", "created_at", "id"]},
        ),
        migrations.CreateModel(
            name="EvaluationRound",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("open", "Open"), ("closed", "Closed")], default="draft", max_length=20)),
                ("feedback_summary", models.TextField(blank=True)),
                ("opens_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="closed_evaluation_rounds", to=settings.AUTH_USER_MODEL)),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="rounds", to="evaluations.evaluationexercise")),
                ("opened_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="opened_evaluation_rounds", to=settings.AUTH_USER_MODEL)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_rounds", to="organisations.organisation")),
            ],
            options={"ordering": ["number", "created_at"]},
        ),
        migrations.CreateModel(
            name="EvaluationSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted")], default="draft", max_length=20)),
                ("confidence", models.PositiveSmallIntegerField(default=3)),
                ("overall_rationale", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_submissions", to="organisations.organisation")),
                ("round", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="evaluations.evaluationround")),
                ("submitted_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluation_submissions", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["created_at", "id"]},
        ),
        migrations.CreateModel(
            name="MinorityReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("analysis", models.TextField()),
                ("recommendation", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published")], default="published", max_length=20)),
                ("published_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="minority_reports", to=settings.AUTH_USER_MODEL)),
                ("exercise", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="minority_reports", to="evaluations.evaluationexercise")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="minority_reports", to="organisations.organisation")),
                ("round", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="minority_reports", to="evaluations.evaluationround")),
            ],
            options={"ordering": ["-published_at", "id"]},
        ),
        migrations.CreateModel(
            name="PortfolioCriterion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("weight", models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ("higher_is_better", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_criteria", to="organisations.organisation")),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="criteria", to="evaluations.prioritisationportfolio")),
            ],
            options={"ordering": ["order", "created_at"]},
        ),
        migrations.CreateModel(
            name="PortfolioCandidate",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("budget_required", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("capacity_required", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("mandatory", models.BooleanField(default=False)),
                ("rationale", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("withdrawn", "Withdrawn")], default="active", max_length=20)),
                ("added_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="added_portfolio_candidates", to=settings.AUTH_USER_MODEL)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_candidates", to="decisions.decision")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_candidates", to="organisations.organisation")),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="candidates", to="evaluations.prioritisationportfolio")),
            ],
            options={"ordering": ["-mandatory", "decision__title", "id"]},
        ),
        migrations.CreateModel(
            name="EvaluationResponse",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ("vote", models.CharField(blank=True, choices=[("approve", "Approve"), ("consent", "Consent"), ("concern", "Concern"), ("object", "Object"), ("abstain", "Abstain")], max_length=20)),
                ("rationale", models.TextField(blank=True)),
                ("criterion", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="evaluations.evaluationcriterion")),
                ("option", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_responses", to="decision_options.decisionoption")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="evaluation_responses", to="organisations.organisation")),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="responses", to="evaluations.evaluationsubmission")),
            ],
            options={"ordering": ["option__title", "criterion__order", "created_at"]},
        ),
        migrations.CreateModel(
            name="PortfolioAssessment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.DecimalField(decimal_places=3, max_digits=6)),
                ("confidence", models.PositiveSmallIntegerField(default=3)),
                ("rationale", models.TextField(blank=True)),
                ("assessor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="portfolio_assessments", to=settings.AUTH_USER_MODEL)),
                ("candidate", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="evaluations.portfoliocandidate")),
                ("criterion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assessments", to="evaluations.portfoliocriterion")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_assessments", to="organisations.organisation")),
            ],
            options={"ordering": ["candidate__decision__title", "criterion__order", "assessor__email"]},
        ),
        migrations.CreateModel(
            name="PortfolioSelection",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("selected", models.BooleanField(default=False)),
                ("priority_order", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("approved_budget", models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ("approved_capacity", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ("rationale", models.TextField(blank=True)),
                ("selected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("candidate", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="selection", to="evaluations.portfoliocandidate")),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="portfolio_selections", to="organisations.organisation")),
                ("selected_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="portfolio_selections", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-selected", "priority_order", "candidate__decision__title"]},
        ),
        migrations.AddConstraint(model_name="evaluationexercise", constraint=models.CheckConstraint(condition=models.Q(("quorum_count__gte", 1)), name="evaluation_quorum_positive")),
        migrations.AddConstraint(model_name="evaluationexercise", constraint=models.CheckConstraint(condition=models.Q(("approval_threshold__gte", 0), ("approval_threshold__lte", 100)), name="evaluation_approval_threshold_range")),
        migrations.AddConstraint(model_name="evaluationexercise", constraint=models.CheckConstraint(condition=models.Q(("objection_threshold__gte", 0), ("objection_threshold__lte", 100)), name="evaluation_objection_threshold_range")),
        migrations.AddIndex(model_name="evaluationexercise", index=models.Index(fields=["organisation", "status", "-updated_at"], name="evaluation_org_status_idx")),
        migrations.AddIndex(model_name="evaluationexercise", index=models.Index(fields=["decision", "status"], name="evaluation_decision_status_idx")),
        migrations.AddConstraint(model_name="evaluationcriterion", constraint=models.UniqueConstraint(fields=("exercise", "title"), name="unique_evaluation_criterion_title")),
        migrations.AddConstraint(model_name="evaluationcriterion", constraint=models.CheckConstraint(condition=models.Q(("weight__gt", 0)), name="evaluation_criterion_weight_positive")),
        migrations.AddConstraint(model_name="evaluationcriterion", constraint=models.CheckConstraint(condition=models.Q(("scale_max__gt", models.F("scale_min"))), name="evaluation_criterion_scale_ordered")),
        migrations.AddConstraint(model_name="evaluationround", constraint=models.UniqueConstraint(fields=("exercise", "number"), name="unique_evaluation_round_number")),
        migrations.AddConstraint(model_name="evaluationround", constraint=models.UniqueConstraint(condition=models.Q(("status", "open")), fields=("exercise",), name="one_open_round_per_exercise")),
        migrations.AddConstraint(model_name="evaluationround", constraint=models.CheckConstraint(condition=models.Q(("number__gte", 1)), name="evaluation_round_number_positive")),
        migrations.AddConstraint(model_name="evaluationsubmission", constraint=models.UniqueConstraint(fields=("round", "submitted_by"), name="one_submission_per_round_user")),
        migrations.AddConstraint(model_name="evaluationsubmission", constraint=models.CheckConstraint(condition=models.Q(("confidence__gte", 1), ("confidence__lte", 5)), name="evaluation_submission_confidence_range")),
        migrations.AddConstraint(model_name="portfoliocriterion", constraint=models.UniqueConstraint(fields=("portfolio", "title"), name="unique_portfolio_criterion_title")),
        migrations.AddConstraint(model_name="portfoliocriterion", constraint=models.CheckConstraint(condition=models.Q(("weight__gt", 0)), name="portfolio_criterion_weight_positive")),
        migrations.AddConstraint(model_name="portfoliocandidate", constraint=models.UniqueConstraint(fields=("portfolio", "decision"), name="unique_decision_per_priority_portfolio")),
        migrations.AddConstraint(model_name="portfoliocandidate", constraint=models.CheckConstraint(condition=models.Q(("budget_required__gte", 0)), name="candidate_budget_nonnegative")),
        migrations.AddConstraint(model_name="portfoliocandidate", constraint=models.CheckConstraint(condition=models.Q(("capacity_required__gte", 0)), name="candidate_capacity_nonnegative")),
        migrations.AddConstraint(model_name="evaluationresponse", constraint=models.UniqueConstraint(condition=models.Q(("criterion__isnull", False)), fields=("submission", "option", "criterion"), name="unique_scored_response")),
        migrations.AddConstraint(model_name="evaluationresponse", constraint=models.UniqueConstraint(condition=models.Q(("criterion__isnull", True)), fields=("submission", "option"), name="unique_ballot_response")),
        migrations.AddConstraint(model_name="portfolioassessment", constraint=models.UniqueConstraint(fields=("candidate", "criterion", "assessor"), name="unique_portfolio_assessment")),
        migrations.AddConstraint(model_name="portfolioassessment", constraint=models.CheckConstraint(condition=models.Q(("score__gte", 0), ("score__lte", 100)), name="portfolio_score_range")),
        migrations.AddConstraint(model_name="portfolioassessment", constraint=models.CheckConstraint(condition=models.Q(("confidence__gte", 1), ("confidence__lte", 5)), name="portfolio_confidence_range")),
        migrations.AddIndex(model_name="prioritisationportfolio", index=models.Index(fields=["organisation", "status", "-updated_at"], name="priority_portfolio_org_idx")),
    ]
