# Generated by Django 5.2.17 on 2026-08-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationexercise',
            name='blind_applicant_identity',
            field=models.BooleanField(default=False, help_text="Hide option titles/descriptions from reviewers during scoring, showing 'Application A/B/…' instead."),
        ),
        migrations.AddField(
            model_name='evaluationresponse',
            name='rank',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluationexercise',
            name='method',
            field=models.CharField(choices=[('scorecard', 'Multi-criteria scorecard'), ('approval', 'Approval voting'), ('consent', 'Consent and objections'), ('delphi', 'Delphi evaluation'), ('ranked_choice', 'Ranked-choice (instant runoff)')], default='scorecard', max_length=24),
        ),
    ]
