# Generated by Django 5.2.17 on 2026-09-26 22:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decisions", "0004_decision_organisation_method"),
        (
            "evaluations",
            "0003_alter_evaluationexercise_method_forecastquestion_and_more",
        ),
        ("organisations", "0002_administration_and_membership_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationexercise",
            name="voice_credit_budget",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Quadratic voting only: credits each participant may spend across their ballot.",
            ),
        ),
        migrations.AddField(
            model_name="evaluationresponse",
            name="quadratic_votes",
            field=models.IntegerField(
                blank=True,
                help_text="Signed vote count for a quadratic-voting ballot; positive supports, negative opposes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="evaluationexercise",
            name="method",
            field=models.CharField(
                choices=[
                    ("scorecard", "Multi-criteria scorecard"),
                    ("approval", "Approval voting"),
                    ("consent", "Consent and objections"),
                    ("delphi", "Delphi evaluation"),
                    ("ranked_choice", "Ranked-choice (instant runoff)"),
                    ("forecasting", "Calibrated forecasting"),
                    ("quadratic", "Quadratic voting"),
                ],
                default="scorecard",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationexercise",
            constraint=models.CheckConstraint(
                condition=models.Q(("voice_credit_budget__gte", 1)),
                name="evaluation_voice_credit_budget_positive",
            ),
        ),
    ]
