# Generated by Django 5.2.17 on 2026-09-26 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("decision_options", "0003_decisionoption_awarded_amount_and_more"),
        ("evaluations", "0004_evaluationexercise_voice_credit_budget_and_more"),
        ("organisations", "0002_administration_and_membership_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationexercise",
            name="method",
            field=models.CharField(
                choices=[
                    ("scorecard", "Multi-criteria scorecard"),
                    ("approval", "Approval voting"),
                    ("consent", "Consent and objections"),
                    ("delphi", "Delphi evaluation"),
                    ("ranked_choice", "Ranked-choice (instant runoff)"),
                    ("forecasting", "Calibrated forecasting"),
                    ("quadratic", "Quadratic voting"),
                    ("liquid_democracy", "Liquid democracy"),
                ],
                default="scorecard",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="LiquidVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delegate_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquid_delegations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquid_votes",
                        to="evaluations.evaluationexercise",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquid_votes",
                        to="decision_options.decisionoption",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquid_votes",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liquid_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["exercise", "delegate_to"],
                        name="liquid_vote_delegate_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("exercise", "voter"),
                        name="unique_liquid_vote_per_exercise_voter",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("delegate_to__isnull", True), ("option__isnull", False)
                            ),
                            models.Q(
                                ("delegate_to__isnull", False), ("option__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="liquid_vote_exactly_one_choice",
                    ),
                ],
            },
        ),
    ]
