# Generated by Django 5.2.17 on 2026-09-26 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0005_alter_evaluationexercise_method_liquidvote"),
        ("organisations", "0002_administration_and_membership_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="evaluationexercise",
            name="method",
            field=models.CharField(
                choices=[
                    ("scorecard", "Multi-criteria scorecard"),
                    ("approval", "Approval voting"),
                    ("consent", "Consent and objections"),
                    ("delphi", "Delphi evaluation"),
                    ("ranked_choice", "Ranked-choice (instant runoff)"),
                    ("forecasting", "Calibrated forecasting"),
                    ("quadratic", "Quadratic voting"),
                    ("liquid_democracy", "Liquid democracy"),
                    ("opinion_clustering", "Opinion clustering"),
                ],
                default="scorecard",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="OpinionStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.CharField(max_length=500)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opinion_statements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinion_statements",
                        to="evaluations.evaluationexercise",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinion_statements",
                        to="organisations.organisation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="OpinionVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "choice",
                    models.CharField(
                        choices=[("agree", "Agree"), ("disagree", "Disagree")],
                        max_length=20,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opinion_votes",
                        to="organisations.organisation",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="evaluations.opinionstatement",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="opinion_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="opinionstatement",
            index=models.Index(
                fields=["exercise", "created_at"], name="opinion_statement_exercise_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="opinionvote",
            constraint=models.UniqueConstraint(
                fields=("statement", "voter"),
                name="one_opinion_vote_per_statement_voter",
            ),
        ),
    ]
