# Generated by Django 5.2.17 on 2026-08-22 08:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0002_administration_and_membership_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationLookupConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_key', models.CharField(choices=[('manual', 'Manual verification'), ('candid', 'Candid (GuideStar)')], default='manual', max_length=20)),
                ('api_key_encrypted', models.TextField(blank=True, default='')),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lookup_configuration', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'organisation lookup configuration',
                'constraints': [models.CheckConstraint(condition=models.Q(('provider_key__in', ['manual', 'candid'])), name='lookup_provider_key_valid')],
            },
        ),
    ]
