# Generated manually for Phase 12.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("foresight", "0002_feed_subscriptions"),
        ("decisions", "0003_decision_template_provenance"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForesightCanvas",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                ("focal_question", models.TextField()),
                ("scope", models.TextField()),
                ("horizon_year", models.PositiveSmallIntegerField()),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("complete", "Complete"), ("archived", "Archived")], default="draft", max_length=20)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_foresight_canvases", to=settings.AUTH_USER_MODEL)),
                ("organisation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="foresight_canvases", to="organisations.organisation")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_foresight_canvases", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-updated_at", "title"]},
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField()),
                ("driver_type", models.CharField(choices=[("trend", "Trend"), ("driver", "Driver of change"), ("critical_uncertainty", "Critical uncertainty"), ("predetermined", "Predetermined element"), ("wild_card", "Wild card")], max_length=30)),
                ("steep_category", models.CharField(choices=[("social", "Social"), ("technological", "Technological"), ("economic", "Economic"), ("environmental", "Environmental"), ("political", "Political"), ("legal", "Legal"), ("ethical", "Ethical")], max_length=30)),
                ("direction", models.CharField(choices=[("increasing", "Increasing"), ("decreasing", "Decreasing"), ("stable", "Stable"), ("volatile", "Volatile"), ("unclear", "Unclear")], default="unclear", max_length=20)),
                ("impact", models.PositiveSmallIntegerField(default=3)),
                ("uncertainty", models.PositiveSmallIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("canvas", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="drivers", to="foresight.foresightcanvas")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_foresight_drivers", to=settings.AUTH_USER_MODEL)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_foresight_drivers", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-impact", "-uncertainty", "title"]},
        ),
        migrations.CreateModel(
            name="SystemStakeholder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=240)),
                ("stakeholder_type", models.CharField(choices=[("internal", "Internal"), ("customer", "Customer or beneficiary"), ("partner", "Partner"), ("regulator", "Regulator or government"), ("community", "Community"), ("competitor", "Competitor"), ("other", "Other")], max_length=30)),
                ("role", models.TextField()),
                ("interests", models.TextField()),
                ("influence", models.PositiveSmallIntegerField(default=3)),
                ("exposure", models.PositiveSmallIntegerField(default=3)),
                ("stance", models.CharField(choices=[("supportive", "Supportive"), ("neutral", "Neutral"), ("resistant", "Resistant"), ("mixed", "Mixed"), ("unclear", "Unclear")], default="unclear", max_length=20)),
                ("canvas", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stakeholders", to="foresight.foresightcanvas")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_system_stakeholders", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-influence", "name"]},
        ),
        migrations.CreateModel(
            name="ThreeHorizonItem",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("horizon", models.CharField(choices=[("h1", "Horizon 1 - current system"), ("h2", "Horizon 2 - transition"), ("h3", "Horizon 3 - emerging future")], max_length=10)),
                ("title", models.CharField(max_length=260)),
                ("description", models.TextField()),
                ("evidence", models.TextField(blank=True)),
                ("canvas", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="horizon_items", to="foresight.foresightcanvas")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_three_horizon_items", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["horizon", "title"]},
        ),
        migrations.CreateModel(
            name="FuturesWheelConsequence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=260)),
                ("description", models.TextField()),
                ("order", models.PositiveSmallIntegerField(default=1)),
                ("consequence_type", models.CharField(choices=[("opportunity", "Opportunity"), ("threat", "Threat"), ("mixed", "Mixed"), ("unclear", "Unclear")], default="unclear", max_length=20)),
                ("likelihood", models.PositiveSmallIntegerField(default=3)),
                ("impact", models.PositiveSmallIntegerField(default=3)),
                ("canvas", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="consequences", to="foresight.foresightcanvas")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_futures_consequences", to=settings.AUTH_USER_MODEL)),
                ("originating_driver", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="consequences", to="foresight.driver")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="foresight.futureswheelconsequence")),
            ],
            options={"ordering": ["order", "-impact", "title"]},
        ),
        migrations.CreateModel(
            name="CausalRelationship",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("polarity", models.CharField(choices=[("reinforcing", "Reinforcing"), ("balancing", "Balancing"), ("uncertain", "Uncertain")], max_length=20)),
                ("strength", models.PositiveSmallIntegerField(default=3)),
                ("delay", models.CharField(choices=[("immediate", "Immediate"), ("short", "Short delay"), ("medium", "Medium delay"), ("long", "Long delay"), ("unknown", "Unknown")], default="unknown", max_length=20)),
                ("rationale", models.TextField()),
                ("canvas", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="relationships", to="foresight.foresightcanvas")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_causal_relationships", to=settings.AUTH_USER_MODEL)),
                ("source_driver", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="outgoing_relationships", to="foresight.driver")),
                ("target_driver", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="incoming_relationships", to="foresight.driver")),
            ],
            options={"ordering": ["source_driver__title", "target_driver__title"]},
        ),
        migrations.CreateModel(
            name="DriverSignal",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rationale", models.CharField(max_length=1000)),
                ("driver", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="signal_links", to="foresight.driver")),
                ("linked_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="linked_driver_signals", to=settings.AUTH_USER_MODEL)),
                ("signal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="driver_links", to="foresight.signal")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="driver",
            name="signals",
            field=models.ManyToManyField(related_name="drivers", through="foresight.DriverSignal", to="foresight.signal"),
        ),
        migrations.CreateModel(
            name="FeedbackLoop",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField()),
                ("loop_type", models.CharField(choices=[("reinforcing", "Reinforcing"), ("balancing", "Balancing"), ("mixed", "Mixed"), ("uncertain", "Uncertain")], max_length=20)),
                ("rationale", models.TextField()),
                ("canvas", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="feedback_loops", to="foresight.foresightcanvas")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_feedback_loops", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["loop_type", "name"]},
        ),
        migrations.CreateModel(
            name="FeedbackLoopDriver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, editable=False),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_loop_links",
                        to="foresight.driver",
                    ),
                ),
                (
                    "feedback_loop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_links",
                        to="foresight.feedbackloop",
                    ),
                ),
            ],
            options={"ordering": ["position", "created_at"]},
        ),
        migrations.AddField(
            model_name="feedbackloop",
            name="drivers",
            field=models.ManyToManyField(
                related_name="feedback_loops",
                through="foresight.FeedbackLoopDriver",
                to="foresight.driver",
            ),
        ),
        migrations.CreateModel(
            name="StrategicImplication",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=260)),
                ("description", models.TextField()),
                ("implication_type", models.CharField(choices=[("opportunity", "Opportunity"), ("threat", "Threat"), ("capability", "Capability requirement"), ("decision_requirement", "Decision requirement"), ("policy", "Policy implication")], max_length=30)),
                ("priority", models.PositiveSmallIntegerField(default=3)),
                ("status", models.CharField(choices=[("open", "Open"), ("addressed", "Addressed"), ("dismissed", "Dismissed")], default="open", max_length=20)),
                ("canvas", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="implications", to="foresight.foresightcanvas")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_strategic_implications", to=settings.AUTH_USER_MODEL)),
                ("drivers", models.ManyToManyField(blank=True, related_name="implications", to="foresight.driver")),
                ("linked_decision", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="foresight_implications", to="decisions.decision")),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_strategic_implications", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-priority", "title"]},
        ),
        migrations.AddConstraint(model_name="foresightcanvas", constraint=models.CheckConstraint(condition=~models.Q(title=""), name="foresight_canvas_title_not_empty")),
        migrations.AddConstraint(model_name="foresightcanvas", constraint=models.CheckConstraint(condition=models.Q(horizon_year__gte=2000, horizon_year__lte=2200), name="foresight_canvas_horizon_year_valid")),
        migrations.AddConstraint(model_name="foresightcanvas", constraint=models.CheckConstraint(condition=models.Q(status__in=["draft", "active", "complete", "archived"]), name="foresight_canvas_status_valid")),
        migrations.AddIndex(model_name="foresightcanvas", index=models.Index(fields=["organisation", "status", "horizon_year"], name="foresight_canvas_org_idx")),
        migrations.AddConstraint(model_name="driver", constraint=models.CheckConstraint(condition=~models.Q(title=""), name="foresight_driver_title_not_empty")),
        migrations.AddConstraint(model_name="driver", constraint=models.CheckConstraint(condition=models.Q(impact__gte=1, impact__lte=5), name="foresight_driver_impact_valid")),
        migrations.AddConstraint(model_name="driver", constraint=models.CheckConstraint(condition=models.Q(uncertainty__gte=1, uncertainty__lte=5), name="foresight_driver_uncertainty_valid")),
        migrations.AddConstraint(model_name="driver", constraint=models.CheckConstraint(condition=models.Q(driver_type__in=["trend", "driver", "critical_uncertainty", "predetermined", "wild_card"]), name="foresight_driver_type_valid")),
        migrations.AddConstraint(model_name="driver", constraint=models.CheckConstraint(condition=models.Q(direction__in=["increasing", "decreasing", "stable", "volatile", "unclear"]), name="foresight_driver_direction_valid")),
        migrations.AddConstraint(model_name="driver", constraint=models.UniqueConstraint(fields=("canvas", "title"), name="unique_driver_title_per_canvas")),
        migrations.AddConstraint(model_name="systemstakeholder", constraint=models.CheckConstraint(condition=~models.Q(name=""), name="system_stakeholder_name_not_empty")),
        migrations.AddConstraint(model_name="systemstakeholder", constraint=models.CheckConstraint(condition=models.Q(influence__gte=1, influence__lte=5), name="system_stakeholder_influence_valid")),
        migrations.AddConstraint(model_name="systemstakeholder", constraint=models.CheckConstraint(condition=models.Q(exposure__gte=1, exposure__lte=5), name="system_stakeholder_exposure_valid")),
        migrations.AddConstraint(model_name="systemstakeholder", constraint=models.UniqueConstraint(fields=("canvas", "name"), name="unique_stakeholder_name_per_canvas")),
        migrations.AddConstraint(model_name="threehorizonitem", constraint=models.CheckConstraint(condition=~models.Q(title=""), name="three_horizon_title_not_empty")),
        migrations.AddConstraint(model_name="threehorizonitem", constraint=models.CheckConstraint(condition=models.Q(horizon__in=["h1", "h2", "h3"]), name="three_horizon_value_valid")),
        migrations.AddConstraint(model_name="threehorizonitem", constraint=models.UniqueConstraint(fields=("canvas", "horizon", "title"), name="unique_horizon_item_per_canvas")),
        migrations.AddConstraint(model_name="futureswheelconsequence", constraint=models.CheckConstraint(condition=models.Q(order__gte=1, order__lte=3), name="futures_consequence_order_valid")),
        migrations.AddConstraint(model_name="futureswheelconsequence", constraint=models.CheckConstraint(condition=models.Q(likelihood__gte=1, likelihood__lte=5), name="futures_consequence_likelihood_valid")),
        migrations.AddConstraint(model_name="futureswheelconsequence", constraint=models.CheckConstraint(condition=models.Q(impact__gte=1, impact__lte=5), name="futures_consequence_impact_valid")),
        migrations.AddConstraint(model_name="causalrelationship", constraint=models.CheckConstraint(condition=models.Q(strength__gte=1, strength__lte=5), name="causal_relationship_strength_valid")),
        migrations.AddConstraint(model_name="causalrelationship", constraint=models.CheckConstraint(condition=~models.Q(source_driver=models.F("target_driver")), name="causal_relationship_not_self")),
        migrations.AddConstraint(model_name="causalrelationship", constraint=models.UniqueConstraint(fields=("canvas", "source_driver", "target_driver"), name="unique_directed_relationship_per_canvas")),
        migrations.AddConstraint(model_name="driversignal", constraint=models.UniqueConstraint(fields=("driver", "signal"), name="unique_signal_per_driver")),
        migrations.AddConstraint(model_name="feedbackloop", constraint=models.CheckConstraint(condition=~models.Q(name=""), name="feedback_loop_name_not_empty")),
        migrations.AddConstraint(model_name="feedbackloop", constraint=models.UniqueConstraint(fields=("canvas", "name"), name="unique_feedback_loop_name_per_canvas")),
        migrations.AddConstraint(
            model_name="feedbackloopdriver",
            constraint=models.CheckConstraint(
                condition=models.Q(position__gte=1),
                name="feedback_loop_driver_position_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedbackloopdriver",
            constraint=models.UniqueConstraint(
                fields=("feedback_loop", "driver"),
                name="unique_driver_per_feedback_loop",
            ),
        ),
        migrations.AddConstraint(
            model_name="feedbackloopdriver",
            constraint=models.UniqueConstraint(
                fields=("feedback_loop", "position"),
                name="unique_position_per_feedback_loop",
            ),
        ),
        migrations.AddConstraint(model_name="strategicimplication", constraint=models.CheckConstraint(condition=~models.Q(title=""), name="strategic_implication_title_not_empty")),
        migrations.AddConstraint(model_name="strategicimplication", constraint=models.CheckConstraint(condition=models.Q(priority__gte=1, priority__lte=5), name="strategic_implication_priority_valid")),
        migrations.AddConstraint(model_name="strategicimplication", constraint=models.CheckConstraint(condition=models.Q(status__in=["open", "addressed", "dismissed"]), name="strategic_implication_status_valid")),
    ]
