# Generated by Django 5.2.16 on 2026-08-03 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assumptions', '0001_initial'),
        ('foresight', '0004_scenario_planning'),
        ('risks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignpostAssumptionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rationale', models.TextField()),
                ('assumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signpost_links', to='assumptions.assumption')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_signpost_assumptions', to=settings.AUTH_USER_MODEL)),
                ('signpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumption_links', to='foresight.signpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('signpost', 'assumption'), name='unique_signpost_assumption_link')],
            },
        ),
        migrations.CreateModel(
            name='SignpostRiskLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rationale', models.TextField()),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_signpost_risks', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signpost_links', to='risks.risk')),
                ('signpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_links', to='foresight.signpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('signpost', 'risk'), name='unique_signpost_risk_link')],
            },
        ),
    ]
