# Generated by Django 5.2.17 on 2026-09-02 22:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisions', '0004_decision_organisation_method'),
        ('foresight', '0007_sourceattachment_infected_status'),
        ('organisations', '0002_administration_and_membership_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='accessed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='archived_url',
            field=models.URLField(blank=True, max_length=1200),
        ),
        migrations.AddField(
            model_name='source',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='source',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='review_due_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ResearchClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement', models.TextField()),
                ('state', models.CharField(choices=[('demonstrated', 'Demonstrated'), ('supported', 'Supported'), ('plausible', 'Plausible'), ('unknown', 'Unknown'), ('contradicted', 'Contradicted')], default='unknown', max_length=20)),
                ('recommendation', models.CharField(choices=[('build', 'Build'), ('integrate', 'Integrate'), ('defer', 'Defer'), ('avoid', 'Avoid'), ('monitor', 'Monitor')], default='defer', max_length=20)),
                ('relevance', models.CharField(choices=[('facilitation', 'Facilitation'), ('platform', 'Platform'), ('operations', 'Operations'), ('mixed', 'Mixed')], default='platform', max_length=20)),
                ('evidence_summary', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('assumptions', models.TextField(blank=True)),
                ('reversal_conditions', models.TextField(blank=True)),
                ('expected_outcome', models.TextField(blank=True)),
                ('authority_score', models.PositiveSmallIntegerField(default=0)),
                ('directness_score', models.PositiveSmallIntegerField(default=0)),
                ('recency_score', models.PositiveSmallIntegerField(default=0)),
                ('triangulation_score', models.PositiveSmallIntegerField(default=0)),
                ('review_due_on', models.DateField(blank=True, null=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('lifecycle_status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_research_claims', to=settings.AUTH_USER_MODEL)),
                ('linked_decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='research_claims', to='decisions.decision')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_claims', to='organisations.organisation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_research_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lifecycle_status', 'review_due_on', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchClaimSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('context', 'Context only')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_links', to='foresight.researchclaim')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_research_sources', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_links', to='foresight.source')),
            ],
            options={
                'ordering': ['relationship', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='researchclaim',
            name='sources',
            field=models.ManyToManyField(related_name='research_claims', through='foresight.ResearchClaimSource', to='foresight.source'),
        ),
        migrations.AddConstraint(
            model_name='researchclaimsource',
            constraint=models.UniqueConstraint(fields=('claim', 'source'), name='unique_research_claim_source'),
        ),
        migrations.AddIndex(
            model_name='researchclaim',
            index=models.Index(fields=['organisation', 'lifecycle_status', 'state'], name='foresight_claim_org_idx'),
        ),
        migrations.AddIndex(
            model_name='researchclaim',
            index=models.Index(fields=['organisation', 'review_due_on'], name='foresight_claim_review_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchclaim',
            constraint=models.CheckConstraint(condition=models.Q(('statement', ''), _negated=True), name='foresight_claim_statement_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='researchclaim',
            constraint=models.CheckConstraint(condition=models.Q(('authority_score__lte', 3)), name='foresight_claim_authority_max'),
        ),
        migrations.AddConstraint(
            model_name='researchclaim',
            constraint=models.CheckConstraint(condition=models.Q(('directness_score__lte', 3)), name='foresight_claim_directness_max'),
        ),
        migrations.AddConstraint(
            model_name='researchclaim',
            constraint=models.CheckConstraint(condition=models.Q(('recency_score__lte', 2)), name='foresight_claim_recency_max'),
        ),
        migrations.AddConstraint(
            model_name='researchclaim',
            constraint=models.CheckConstraint(condition=models.Q(('triangulation_score__lte', 2)), name='foresight_claim_triangulation_max'),
        ),
    ]
